### ISSUE TITLE
Wrong answer of search.json

### ISSUE THREAD

**Issue by olegsuv** [ukraine-blacklist/platform#2]
https://pacific-oasis-63187.herokuapp.com/api/v1/estate/advertisement/search.json?phones%5B%5D=0505169015&phones%5B%5D=0977076113&url=%2Fobyavlenie%2Ftepla-3h-pokraschenogo-planuvannya-IDxWbHU.html - 0 items

https://pacific-oasis-63187.herokuapp.com/api/v1/estate/advertisement/search.json?phones%5B%5D=0505169015&phones%5B%5D=0977076113&url=%2Fobyavlenie%2F2-h-komnatnaya-kvartira-uluchshenoy-planirovki-IDvDNii.html - 6 items

Phones are the same.

Actual result: answer based on match phones && url (and)
Expected result: answer based on match phones || url (or)

**Comment by ReenExe** [comment]
Hi, all fine, already use "or"
Changes: add "normalize" before search by phone in database
So 050 *** ** ** -> 38 050 *** ** ** and fined
